// frontend/src/lib/components/tool-renderers/WriteFileRenderer.svelte
<script lang="ts">
	let { args = {}, result = undefined, status = 'running' }: {
		args: Record<string, unknown>;
		result?: Record<string, unknown> | string;
		status: 'running' | 'done' | 'error';
	} = $props();

	let path = $derived(args.path as string || '');
	let isError = $derived(status === 'error');
	let errorMsg = $derived.by(() => {
		if (!isError || !result) return '';
		if (typeof result === 'string') return result;
		return (result as Record<string, unknown>).error as string || '';
	});
</script>

{#if isError}
	<p class="text-xs text-destructive mt-1" dir="ltr">{errorMsg}</p>
{:else if status === 'done'}
	<p class="text-[10px] text-green-400/80 mt-1">✓ <span class="thaana">ފައިލް ލިޔެވިއްޖެ:</span> <span class="font-mono" dir="ltr">{path}</span></p>
{/if}

// apps/desktop/src/renderer/components/tool-renderers/WriteFileRenderer.tsx
import React from 'react';

interface WriteFileRendererProps {
	args: Record<string, unknown>;
	result?: Record<string, unknown> | string;
	status: 'running' | 'done' | 'error';
}

export function WriteFileRenderer({ args, result, status }: WriteFileRendererProps) {
	const path = (args.path as string) || '';
	const isError = status === 'error';
	const errorMsg = isError && result
		? (typeof result === 'string' ? result : (result as Record<string, unknown>).error as string || '')
		: '';

	if (isError) {
		return <p className="text-xs text-destructive mt-1" dir="ltr">{errorMsg}</p>;
	}

	if (status === 'done') {
		return (
			<p className="text-[10px] text-green-400/80 mt-1">
				✓ <span className="thaana">ފައިލް ލިޔެވިއްޖެ:</span>{' '}
				<span className="font-mono" dir="ltr">{path}</span>
			</p>
		);
	}

	return null;
}
