// frontend/src/lib/components/LandingPage.svelte
<script lang="ts">
	import { ChevronDown } from 'lucide-svelte';
	import MockCodeExecution from './landing-mocks/MockCodeExecution.svelte';
	import MockArtifactGeneration from './landing-mocks/MockArtifactGeneration.svelte';
	import MockRecipe from './landing-mocks/MockRecipe.svelte';
	import MockWebSearch from './landing-mocks/MockWebSearch.svelte';
	import MockMessageDraft from './landing-mocks/MockMessageDraft.svelte';
	import MockMultiModel from './landing-mocks/MockMultiModel.svelte';

	function inview(node: HTMLElement) {
		node.style.opacity = '0';
		node.style.transform = 'translateY(24px)';
		node.style.transitionProperty = 'opacity, transform';
		node.style.transitionDuration = '0.6s';
		node.style.transitionTimingFunction = 'ease-out';

		const observer = new IntersectionObserver(
			([entry]) => {
				if (entry.isIntersecting) {
					node.style.opacity = '1';
					node.style.transform = 'translateY(0)';
					observer.unobserve(node);
				}
			},
			{ threshold: 0.1 }
		);
		observer.observe(node);
		return { destroy: () => observer.disconnect() };
	}
</script>

<div class="overflow-y-auto h-screen scroll-smooth">

	<!-- ═══════════════════ HERO ═══════════════════ -->
	<section class="relative flex flex-col items-center justify-center h-screen px-6 overflow-hidden">

		<!-- Background image -->
		<div
			class="absolute inset-0 bg-cover bg-center bg-no-repeat"
			style="background-image: url('/hero.jpg')"
		></div>
		<!-- Gradient overlay for readability -->
		<div class="absolute inset-0 bg-gradient-to-b from-background/70 via-background/50 to-background"></div>

		<!-- Wave logo -->
		<div class="relative z-10 animate-fade-in mb-8" style="animation-delay: 100ms">
			<svg viewBox="0 0 44 28" width="120" height="76" class="text-primary overflow-visible">
				<g clip-path="url(#wc-hero)">
					<path
						d="M-20,8 Q-15,4 -10,8 Q-5,12 0,8 Q5,4 10,8 Q15,12 20,8 Q25,4 30,8 Q35,12 40,8 Q45,4 50,8 Q55,12 60,8"
						fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" opacity="0.7"
					>
						<animateTransform attributeName="transform" type="translate"
							values="0,0;-20,0" dur="2s" repeatCount="indefinite" />
					</path>
					<path
						d="M-20,14 Q-15,10 -10,14 Q-5,18 0,14 Q5,10 10,14 Q15,18 20,14 Q25,10 30,14 Q35,18 40,14 Q45,10 50,14 Q55,18 60,14"
						fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" opacity="0.45"
					>
						<animateTransform attributeName="transform" type="translate"
							values="0,0;-20,0" dur="3s" repeatCount="indefinite" />
					</path>
					<path
						d="M-20,20 Q-15,16 -10,20 Q-5,24 0,20 Q5,16 10,20 Q15,24 20,20 Q25,16 30,20 Q35,24 40,20 Q45,16 50,20 Q55,24 60,20"
						fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" opacity="0.25"
					>
						<animateTransform attributeName="transform" type="translate"
							values="0,0;-20,0" dur="4s" repeatCount="indefinite" />
					</path>
				</g>
				<defs>
					<clipPath id="wc-hero">
						<rect x="0" y="0" width="44" height="28" />
					</clipPath>
				</defs>
			</svg>
		</div>

		<!-- Heading -->
		<h1 class="relative z-10 thaana-heading text-[120px] sm:text-[160px] font-normal leading-none animate-greeting-in">
			<span class="bg-gradient-to-l from-primary via-primary/80 to-foreground bg-clip-text text-transparent">
				ރާޅު
			</span>
		</h1>

		<!-- Tagline -->
		<p
			class="relative z-10 thaana text-2xl sm:text-3xl text-muted-foreground mt-6 animate-fade-in-up"
			style="animation-delay: 200ms"
		>
			ދިވެހި ބަހުގެ އެންމެ ކުޅަދާނަ އޭ.އައި
		</p>

		<!-- Sub-tagline -->
		<p
			class="relative z-10 thaana text-lg sm:text-xl text-muted-foreground/60 mt-3 animate-fade-in-up"
			style="animation-delay: 350ms"
		>
			ލިޔުން، ތަރުޖަމާ، ދިރާސާ — ހުރިހާ ކަމެއް ދިވެހިން
		</p>

		<!-- Sign in CTA -->
		<div class="relative z-10 mt-10 animate-fade-in-up" style="animation-delay: 500ms">
			<a
				href="/login"
				class="thaana inline-block px-10 py-4 bg-primary text-primary-foreground font-semibold text-xl
					rounded-xl hover:bg-primary/90 transition-colors duration-150"
			>
				ގޫގުލް އިން ފައްޓާ
			</a>
		</div>

		<!-- Scroll indicator -->
		<a
			href="#features"
			class="absolute bottom-8 z-10 animate-fade-in"
			style="animation-delay: 900ms"
		>
			<ChevronDown class="w-6 h-6 text-muted-foreground/40 animate-bounce" />
		</a>
	</section>

	<!-- ═══════════════════ FEATURES ═══════════════════ -->
	<section id="features" class="py-28 sm:py-36">

<!-- ── Feature 1: Free Usage (full-wide, centered) ── -->
		<div use:inview class="px-6 mb-28 sm:mb-36">
			<div class="max-w-4xl mx-auto">
				<div
					class="w-full rounded-2xl border border-border/50 overflow-hidden bg-cover bg-bottom bg-no-repeat relative aspect-[3/4] md:aspect-video"
					style="background-image: url('/sections/whale_bg.jpg')"
				>
					<div class="absolute inset-0 flex flex-col items-center justify-start pt-[6%] px-6 pb-[8%] text-center">
						<h3 class="thaana-heading text-9xl font-normal mb-4 leading-tight text-primary-foreground">ހިލޭ ބޭނުންކުރެވޭ</h3>
						<p class="thaana text-lg sm:text-xl text-primary-foreground/70 max-w-2xl mx-auto">
							ގޫގުލް އެކައުންޓެއް ހުރިއްޔާ ނިމުނީ. ރެޖިސްޓްރޭޝަނެއް، ފީ އެއް ނެތް
						</p>
						<img src="/sections/whale_new.png" alt="" class="mt-auto w-[78%] max-w-[520px] object-contain pointer-events-none" />
					</div>
				</div>
			</div>
		</div>

		<!-- ── Feature 2: Code Executable (text left, image right) ── -->
		<div use:inview class="px-6 mb-28 sm:mb-36">
			<div class="max-w-6xl mx-auto grid grid-cols-1 lg:grid-cols-2 gap-12 lg:gap-16 items-center">
				<!-- Text -->
				<div class="order-2 lg:order-1">
					<h3 class="thaana-heading text-8xl sm:text-9xl font-normal mb-4 leading-tight">ފުލް އޭޖެންޓިކް</h3>
					<p class="thaana text-lg text-muted-foreground">
						ހިސާބު ޖަހާ، ޑޭޓާ އެނަލައިޒް ކޮށް، ޗާޓް ހެދޭ.
						ލޯނު ކެލްކިއުލޭޓް ކުރުން، ބަޖެޓް ބެލެހެއްޓުން، ނަތީޖާ ރިވިއު ކުރުން.
						ކޯޑް ލިޔާކަށް ނޭނގުނަސް — ބުނީމަ ހައްދައިދޭ
					</p>
				</div>
				<!-- Image with mock overlay -->
				<div class="order-1 lg:order-2">
					<div
						class="aspect-[4/3] rounded-2xl border border-border/50 overflow-hidden relative bg-cover bg-center bg-no-repeat"
						style="background-image: url('/sections/python.jpg')"
					>
						<div class="absolute inset-0 flex items-center justify-center p-6 sm:p-8">
							<div class="w-full max-w-sm mock-perspective-right">
								<MockCodeExecution />
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>

		<!-- ── Feature 3: Artifact Generation (text right, image left) ── -->
		<div use:inview class="px-6 mb-28 sm:mb-36">
			<div class="max-w-6xl mx-auto grid grid-cols-1 lg:grid-cols-2 gap-12 lg:gap-16 items-center">
				<!-- Image with mock overlay -->
				<div class="order-1">
					<div
						class="aspect-[4/3] rounded-2xl border border-border/50 overflow-hidden relative bg-cover bg-center bg-no-repeat"
						style="background-image: url('/sections/document.jpg')"
					>
						<div class="absolute inset-0 flex items-center justify-center p-6 sm:p-8">
							<div class="w-full max-w-sm mock-perspective-left">
								<MockArtifactGeneration />
							</div>
						</div>
					</div>
				</div>
				<!-- Text -->
				<div class="order-2">
					<h3 class="thaana-heading text-8xl sm:text-9xl font-normal mb-4 leading-tight">ޑޮކިއުމެންޓް ހެދޭ</h3>
					<p class="thaana text-lg text-muted-foreground">
						ވޯޑް، ޕީ.ޑީ.އެފް، އެކްސެލް ފައިލް ހަދައި ޑައުންލޯޑް ކުރެވޭ.
						ފޯމެޓިންގ އާއި ޗާޓާ އެކު ރީތިކޮށް ތައްޔާރުކޮށްދޭ.
						ސިޓީ، ރިޕޯޓް، އިންވޮއިސް — ކޮންމެ ޑޮކިއުމެންޓެއް ވެސް ސީދާ ޗެޓުން
					</p>
				</div>
			</div>
		</div>

		<!-- ── Feature 4: Recipes (text left, image right) ── -->
		<div use:inview class="px-6 mb-28 sm:mb-36">
			<div class="max-w-6xl mx-auto grid grid-cols-1 lg:grid-cols-2 gap-12 lg:gap-16 items-center">
				<!-- Text -->
				<div class="order-2 lg:order-1">
					<h3 class="thaana-heading text-8xl sm:text-9xl font-normal mb-4 leading-tight">ރޯދަ ރެޑީ</h3>
					<p class="thaana text-lg text-muted-foreground">
						ބޭނުން ރެސިޕީއެއް ކެއްކުމަށް ބޭނުންވާ ތަކެތި އަދި ތައްޔާރު ކުރާނެ ސްޓެޕްތައް.
						ޓައިމަރާ އެކު ކޮންމެ ސްޓެޕެއް ފޮލޯ ކުރެވޭ.
						ރޯދަ ވީއްލުމާ ތަރާވީސް — ކޮންމެ ކެއުމެއް ތައްޔާރު ކުރެވޭ
					</p>
				</div>
				<!-- Image with mock overlay -->
				<div class="order-1 lg:order-2">
					<div
						class="aspect-[4/3] rounded-2xl border border-border/50 overflow-hidden relative bg-cover bg-center bg-no-repeat"
						style="background-image: url('/sections/recipe.jpg')"
					>
						<div class="absolute inset-0 flex items-center justify-center p-6 sm:p-8">
							<div class="w-full max-w-sm mock-perspective-right">
								<MockRecipe />
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>

		<!-- ── Minor Feature Cards ── -->
		<div use:inview class="px-6 max-w-6xl mx-auto">
			<div class="grid grid-cols-1 md:grid-cols-3 gap-5">

				<!-- Card: Web Search -->
				<div
					use:inview
					class="bg-card/50 border border-border/50 rounded-2xl overflow-hidden
						hover:border-primary/30 hover:bg-card/80 transition-all duration-300"
				>
					<div class="aspect-[4/3] border-b border-border/30 relative overflow-hidden bg-cover bg-center bg-no-repeat" style="background-image: url('/features/websearch.jpg')">
						<div class="absolute inset-0 flex items-center justify-center p-5">
							<div class="w-full max-w-[220px]">
								<MockWebSearch />
							</div>
						</div>
					</div>
					<div class="p-6">
						<h3 class="thaana-heading text-[48px] font-normal leading-[1.4] mb-2">ވެބް ސާޗް</h3>
						<p class="thaana text-base text-muted-foreground">ގޫގުލް ސާޗް ބޭނުންކޮށް ދިރާސާ ކުރެވޭ</p>
					</div>
				</div>

				<!-- Card: Message Drafting -->
				<div
					use:inview
					class="bg-card/50 border border-border/50 rounded-2xl overflow-hidden
						hover:border-primary/30 hover:bg-card/80 transition-all duration-300"
					style="transition-delay: 100ms"
				>
					<div class="aspect-[4/3] border-b border-border/30 relative overflow-hidden bg-cover bg-center bg-no-repeat" style="background-image: url('/features/documentgeneration.jpg')">
						<div class="absolute inset-0 flex items-center justify-center p-5">
							<div class="w-full max-w-[220px]">
								<MockMessageDraft />
							</div>
						</div>
					</div>
					<div class="p-6">
						<h3 class="thaana-heading text-[48px] font-normal leading-[1.4] mb-2">މެސެޖް ލިޔެދޭ</h3>
						<p class="thaana text-base text-muted-foreground">ސިޓީ، އީމެއިލް، ޓެކްސްޓް މެސެޖް ލިޔެދޭ</p>
					</div>
				</div>

				<!-- Card: Multi Model -->
				<div
					use:inview
					class="bg-card/50 border border-border/50 rounded-2xl overflow-hidden
						hover:border-primary/30 hover:bg-card/80 transition-all duration-300"
					style="transition-delay: 200ms"
				>
					<div class="aspect-[4/3] border-b border-border/30 relative overflow-hidden bg-cover bg-center bg-no-repeat" style="background-image: url('/features/modelchange.jpg')">
						<div class="absolute inset-0 flex items-center justify-center p-5">
							<div class="w-full max-w-[220px]">
								<MockMultiModel />
							</div>
						</div>
					</div>
					<div class="p-6">
						<h3 class="thaana-heading text-[48px] font-normal leading-[1.4] mb-2">މޮޑެލް ބަދަލުކުރެވޭ</h3>
						<p class="thaana text-base text-muted-foreground">ގެމިނީ ގެ ތަފާތު މޮޑެލްތައް ބޭނުންކުރެވޭ</p>
					</div>
				</div>

			</div>
		</div>

	</section>

	<!-- ═══════════════════ FOOTER CTA + FOOTER ═══════════════════ -->
	<div class="relative bg-cover bg-center bg-no-repeat" style="background-image: url('/footer.jpg')">
		<!-- Fade-in from top -->
		<div class="absolute inset-x-0 top-0 h-32 bg-gradient-to-b from-background to-transparent"></div>

		<section class="relative z-10 px-6 py-32 sm:py-40 text-center">
			<div use:inview>
				<h2 class="thaana-heading text-8xl sm:text-9xl mb-6 leading-none text-white">
					ރާޅު ބޭނުން ކުރައްވާ
				</h2>
				<p class="thaana text-xl sm:text-2xl text-white/60 mb-14">
					ހިލޭ، ގޫގުލް އެކައުންޓެއް ހުރިއްޔާ ނިމުނީ
				</p>
				<a
					href="/login"
					class="thaana inline-block px-16 py-6 bg-primary text-primary-foreground font-bold text-3xl
						rounded-2xl hover:brightness-110 transition-all duration-200
						shadow-[0_0_40px_rgba(125,159,227,0.3)] hover:shadow-[0_0_60px_rgba(125,159,227,0.45)]"
				>
					ހިލޭ ފައްޓާ
				</a>
			</div>
		</section>

		<footer class="relative z-10 px-6 py-12">
			<div class="max-w-6xl mx-auto flex flex-col sm:flex-row items-center justify-between gap-6">
				<!-- Brand -->
				<div class="text-center sm:text-start">
					<span class="thaana-heading text-3xl text-white/60">ރާޅު</span>
					<p class="thaana text-sm text-white/30 mt-1">ޖެމިނީ ބޭނުންކޮށް</p>
				</div>
				<!-- Links -->
				<nav class="flex items-center gap-6">
					<a href="/about" class="thaana text-sm text-white/40 hover:text-white/70 transition-colors">
						ރާޅު އާ ބެހޭ
					</a>
					<a href="/privacy" class="thaana text-sm text-white/40 hover:text-white/70 transition-colors">
						ޕްރައިވެސީ
					</a>
					<a href="/terms" class="thaana text-sm text-white/40 hover:text-white/70 transition-colors">
						ޝަރުތުތައް
					</a>
				</nav>
			</div>
		</footer>
	</div>
</div>

<style>
	.mock-perspective-right {
		transform: perspective(1200px) rotateY(-5deg) rotateX(2deg);
		filter: drop-shadow(0 8px 24px rgba(0, 0, 0, 0.3));
	}
	.mock-perspective-left {
		transform: perspective(1200px) rotateY(5deg) rotateX(2deg);
		filter: drop-shadow(0 8px 24px rgba(0, 0, 0, 0.3));
	}

	@media (max-width: 1023px) {
		.mock-perspective-right,
		.mock-perspective-left {
			transform: perspective(1200px) rotateY(-2deg) rotateX(1deg);
		}
	}

	@media (max-width: 639px) {
		.mock-perspective-right,
		.mock-perspective-left {
			transform: none;
			filter: drop-shadow(0 4px 12px rgba(0, 0, 0, 0.2));
		}
	}
</style>

// apps/desktop/src/renderer/LandingPage.tsx
import React, { useRef, useEffect, useState } from "react";

/* ── Wave Logo ── */

function WaveLogo() {
  return (
    <svg viewBox="0 0 44 28" width="120" height="76" className="text-primary overflow-visible">
      <g clipPath="url(#wc-hero)">
        <path
          d="M-20,8 Q-15,4 -10,8 Q-5,12 0,8 Q5,4 10,8 Q15,12 20,8 Q25,4 30,8 Q35,12 40,8 Q45,4 50,8 Q55,12 60,8"
          fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" opacity="0.7"
        >
          <animateTransform attributeName="transform" type="translate"
            values="0,0;-20,0" dur="2s" repeatCount="indefinite" />
        </path>
        <path
          d="M-20,14 Q-15,10 -10,14 Q-5,18 0,14 Q5,10 10,14 Q15,18 20,14 Q25,10 30,14 Q35,18 40,14 Q45,10 50,14 Q55,18 60,14"
          fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" opacity="0.45"
        >
          <animateTransform attributeName="transform" type="translate"
            values="0,0;-20,0" dur="3s" repeatCount="indefinite" />
        </path>
        <path
          d="M-20,20 Q-15,16 -10,20 Q-5,24 0,20 Q5,16 10,20 Q15,24 20,20 Q25,16 30,20 Q35,24 40,20 Q45,16 50,20 Q55,24 60,20"
          fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" opacity="0.25"
        >
          <animateTransform attributeName="transform" type="translate"
            values="0,0;-20,0" dur="4s" repeatCount="indefinite" />
        </path>
      </g>
      <defs>
        <clipPath id="wc-hero">
          <rect x="0" y="0" width="44" height="28" />
        </clipPath>
      </defs>
    </svg>
  );
}

/* ── InViewDiv — animates on scroll into view ── */

function InViewDiv({
  children,
  className = "",
  delay = 0,
}: {
  children: React.ReactNode;
  className?: string;
  delay?: number;
}) {
  const ref = useRef<HTMLDivElement>(null);
  const [visible, setVisible] = useState(false);

  useEffect(() => {
    const el = ref.current;
    if (!el) return;
    const observer = new IntersectionObserver(
      ([entry]) => {
        if (entry.isIntersecting) {
          setVisible(true);
          observer.disconnect();
        }
      },
      { threshold: 0.15 }
    );
    observer.observe(el);
    return () => observer.disconnect();
  }, []);

  return (
    <div
      ref={ref}
      className={className}
      style={{
        opacity: visible ? 1 : 0,
        transform: visible ? "translateY(0)" : "translateY(40px)",
        transition: `opacity 0.6s ease-out ${delay}ms, transform 0.6s ease-out ${delay}ms`,
      }}
    >
      {children}
    </div>
  );
}

/* ── Chevron icon ── */

function ChevronDownIcon({ className }: { className?: string }) {
  return (
    <svg className={className} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
      <path d="m6 9 6 6 6-6" />
    </svg>
  );
}

/* ── Feature card data ── */

interface FeatureCard {
  image: string;
  titleDv: string;
  descDv: string;
}

const FULL_WIDTH_FEATURES: FeatureCard[] = [
  {
    image: "/sections/free.jpg",
    titleDv: "ހިލޭ",
    descDv: "ރާޅު ބޭނުންކުރެވޭނީ ހުރިހާ މީހުންނަށް، ހުރިހާ ވަގުތެއްގައި، ހިލޭ.",
  },
  {
    image: "/sections/python.jpg",
    titleDv: "ޕައިތަން ސޭންޑްބޮކްސް",
    descDv: "ކޯޑު ލިޔެ ރަން ކުރެވޭ — ގްރާފް، ޗާޓް، ޑޭޓާ އެނަލިސިސް.",
  },
  {
    image: "/sections/document.jpg",
    titleDv: "ލިޔެކިޔުން",
    descDv: "ސިޓީ، ރިޕޯޓް، ދިރާސާ — ދިވެހިން ލިޔުންތައް ތައްޔާރުކުރޭ.",
  },
  {
    image: "/sections/recipe.jpg",
    titleDv: "ރެސިޕީ",
    descDv: "ދިވެހި ކެއުންތަކުގެ ރެސިޕީ ހޯދާ، ބައި ބަދަލުކުރޭ.",
  },
];

const SMALL_FEATURES: FeatureCard[] = [
  {
    image: "/features/websearch.jpg",
    titleDv: "ވެބް ސާރޗް",
    descDv: "އެންމެ ފަހުގެ މައުލޫމާތު ހޯދައިދޭ.",
  },
  {
    image: "/features/documentgeneration.jpg",
    titleDv: "ޑޮކިޔުމެންޓް ޖެނެރޭޝަން",
    descDv: "ފައިލް އުފައްދައި ޑައުންލޯޑް ކުރެވޭ.",
  },
  {
    image: "/features/modelchange.jpg",
    titleDv: "މޮޑެލް ބަދަލުކުރޭ",
    descDv: "ތަފާތު އޭ.އައި މޮޑެލްތައް ޚިޔާރުކުރެވޭ.",
  },
];

/* ── Landing Page ── */

interface LandingPageProps {
  onGetStarted: () => void;
}

export default function LandingPage({ onGetStarted }: LandingPageProps) {
  const featuresRef = useRef<HTMLDivElement>(null);

  function scrollToFeatures() {
    featuresRef.current?.scrollIntoView({ behavior: "smooth" });
  }

  return (
    <div className="h-screen overflow-y-auto scroll-smooth">
      {/* Hero section */}
      <section className="relative flex flex-col items-center justify-center h-screen px-6 overflow-hidden shrink-0">
        {/* Background image */}
        <div
          className="absolute inset-0 bg-cover bg-center bg-no-repeat"
          style={{ backgroundImage: "url('/hero.jpg')" }}
        />
        {/* Gradient overlay */}
        <div className="absolute inset-0 bg-gradient-to-b from-background/70 via-background/50 to-background" />

        {/* Wave logo */}
        <div className="relative z-10 animate-fade-in mb-8" style={{ animationDelay: "100ms" }}>
          <WaveLogo />
        </div>

        {/* Heading */}
        <h1 className="relative z-10 thaana-heading text-[120px] sm:text-[160px] font-normal leading-none animate-greeting-in">
          <span className="bg-gradient-to-l from-primary via-primary/80 to-white bg-clip-text text-transparent">
            ރާޅު
          </span>
        </h1>

        {/* Tagline */}
        <p
          className="relative z-10 thaana text-2xl sm:text-3xl text-white mt-6 animate-fade-in-up"
          style={{ animationDelay: "200ms" }}
        >
          ދިވެހި ބަހުގެ އެންމެ ކުޅަދާނަ އޭ.އައި
        </p>

        {/* Sub-tagline */}
        <p
          className="relative z-10 thaana text-lg sm:text-xl text-white/60 mt-3 animate-fade-in-up"
          style={{ animationDelay: "350ms" }}
        >
          ލިޔުން، ތަރުޖަމާ، ދިރާސާ — ހުރިހާ ކަމެއް ދިވެހިން
        </p>

        {/* Sign in CTA */}
        <div className="relative z-10 mt-16 animate-fade-in-up" style={{ animationDelay: "500ms" }}>
          <button
            onClick={onGetStarted}
            className="thaana inline-block px-10 py-4 bg-primary text-primary-foreground font-semibold text-xl
              rounded-xl hover:bg-primary/90 transition-colors duration-150 cursor-pointer"
          >
            ގޫގުލް އިން ފައްޓާ
          </button>
        </div>

        {/* Scroll chevron — hidden while features section is commented out */}
        {/*
        <button
          onClick={scrollToFeatures}
          className="absolute bottom-8 z-10 animate-fade-in text-white/40 hover:text-white/70 transition-colors"
          style={{ animationDelay: "800ms" }}
        >
          <ChevronDownIcon className="w-8 h-8 animate-bounce" />
        </button>
        */}
      </section>

      {/* Features section — commented out, hero only for now */}
      {/*
      <section ref={featuresRef} className="px-6 py-20 max-w-5xl mx-auto" dir="rtl">
        <InViewDiv className="text-center mb-16">
          <h2 className="thaana-heading text-5xl sm:text-6xl text-foreground" style={{ marginTop: 8 }}>
            ކުޅަދާނަ ފީޗާތައް
          </h2>
          <p className="thaana text-lg text-muted-foreground mt-4">
            ރާޅު އަކީ ދިވެހިންނަށް ޚާއްސަ އޭ.އައި ޕްލެޓްފޯމެއް
          </p>
        </InViewDiv>

        <div className="flex flex-col gap-8 mb-12">
          {FULL_WIDTH_FEATURES.map((feat, i) => (
            <InViewDiv key={i} delay={i * 100}>
              <div className="relative rounded-2xl overflow-hidden border border-border bg-card group">
                <div className="relative h-56 sm:h-72 overflow-hidden">
                  <img
                    src={feat.image}
                    alt=""
                    className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-500"
                  />
                  <div className="absolute inset-0 bg-gradient-to-t from-card via-card/30 to-transparent" />
                </div>
                <div className="relative px-6 pb-6 -mt-12 z-10">
                  <h3 className="thaana-heading text-2xl sm:text-3xl text-foreground mb-2" style={{ marginTop: 8 }}>
                    {feat.titleDv}
                  </h3>
                  <p className="thaana text-base text-muted-foreground">
                    {feat.descDv}
                  </p>
                </div>
              </div>
            </InViewDiv>
          ))}
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-3 gap-6 mb-20">
          {SMALL_FEATURES.map((feat, i) => (
            <InViewDiv key={i} delay={i * 100}>
              <div className="rounded-2xl overflow-hidden border border-border bg-card group">
                <div className="relative h-40 overflow-hidden">
                  <img
                    src={feat.image}
                    alt=""
                    className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-500"
                  />
                  <div className="absolute inset-0 bg-gradient-to-t from-card via-card/20 to-transparent" />
                </div>
                <div className="px-4 pb-4 -mt-6 relative z-10">
                  <h4 className="thaana-heading text-lg text-foreground mb-1" style={{ marginTop: 6 }}>
                    {feat.titleDv}
                  </h4>
                  <p className="thaana text-sm text-muted-foreground">
                    {feat.descDv}
                  </p>
                </div>
              </div>
            </InViewDiv>
          ))}
        </div>
      </section>

      <footer className="relative overflow-hidden">
        <div
          className="absolute inset-0 bg-cover bg-center bg-no-repeat"
          style={{ backgroundImage: "url('/footer.jpg')" }}
        />
        <div className="absolute inset-0 bg-background/80" />
        <div className="relative z-10 px-6 py-20 text-center">
          <InViewDiv>
            <WaveLogo />
          </InViewDiv>
          <InViewDiv delay={100}>
            <h3 className="thaana-heading text-4xl text-foreground mt-6" style={{ marginTop: 8 }}>
              ރާޅު
            </h3>
            <p className="thaana text-muted-foreground mt-3 mb-8">
              ދިވެހި ބަހުގެ އެންމެ ކުޅަދާނަ އޭ.އައި
            </p>
            <button
              onClick={onGetStarted}
              className="thaana inline-block px-8 py-3 bg-primary text-primary-foreground font-semibold text-lg
                rounded-xl hover:bg-primary/90 transition-colors duration-150 cursor-pointer"
            >
              މިހާރު ފައްޓާ
            </button>
          </InViewDiv>
        </div>
      </footer>
      */}
    </div>
  );
}
