// frontend/src/lib/components/ChatInput.svelte
<script lang="ts" module>
	export interface AttachedFile {
		id: string;
		file: File;
		type: string;
		preview: string | null;
		uploadStatus: 'pending' | 'uploading' | 'complete';
	}

	export interface PastedContent {
		id: string;
		content: string;
		timestamp: Date;
	}

	export type StyleId = 'normal' | 'learning' | 'concise' | 'explanatory' | 'formal';

	export interface ChatInputSendData {
		message: string;
		files: AttachedFile[];
		pastedContent: PastedContent[];
		webSearchEnabled: boolean;
		style: StyleId;
	}
</script>

<script lang="ts">
	import { Plus, ArrowUp, Archive, X, FileText, Loader2, Sparkles, Paperclip, Camera, Globe, Feather, Check } from 'lucide-svelte';
	import * as DropdownMenu from '$lib/components/ui/dropdown-menu';
	import { modelDisplayName } from '$lib/modes';
	import { Mic, Square } from 'lucide-svelte';
	import { createVoiceRecorder, type VoiceState } from '$lib/voice';
	import { transcribeAudio } from '$lib/transcribe';
	import WaveformVisualizer from './WaveformVisualizer.svelte';

	let {
		value = $bindable(''),
		selectedModel = $bindable('gemini-3-flash-preview'),
		models = [],
		placeholder = 'މެސެޖެއް ލިޔުއްވާ...',
		onSend,
		disabled = false,
		autofocus = false,
	}: {
		value: string;
		selectedModel?: string;
		models?: string[];
		placeholder?: string;
		onSend: (data: ChatInputSendData) => void;
		disabled?: boolean;
		autofocus?: boolean;
	} = $props();

	let files = $state<AttachedFile[]>([]);
	let pastedContent = $state<PastedContent[]>([]);
	let isDragging = $state(false);
	let webSearchEnabled = $state(false);
	let activeStyle = $state<StyleId>('normal');
	let textareaEl = $state<HTMLTextAreaElement | undefined>();
	let fileInputEl = $state<HTMLInputElement | undefined>();

	let voiceState = $state<VoiceState>('idle');
	let recorder = createVoiceRecorder();
	let micPermissionDenied = $state(false);

	export function focus() {
		textareaEl?.focus();
	}

	$effect(() => {
		return () => {
			recorder.destroy();
		};
	});

	const styles: { id: StyleId; label: string }[] = [
		{ id: 'normal', label: 'ނޯމަލް' },
		{ id: 'learning', label: 'ދަސްކުރުން' },
		{ id: 'concise', label: 'ކުރުކޮށް' },
		{ id: 'explanatory', label: 'ތަފްސީލީ' },
		{ id: 'formal', label: 'ރަސްމީ' },
	];

	const hasContent = $derived(value.trim() || files.length > 0 || pastedContent.length > 0);

	// Auto-resize textarea
	$effect(() => {
		value;
		if (textareaEl) {
			textareaEl.style.height = 'auto';
			textareaEl.style.height = Math.min(textareaEl.scrollHeight, 384) + 'px';
		}
	});

	function genId(): string {
		return Math.random().toString(36).slice(2, 11);
	}

	function formatFileSize(bytes: number): string {
		if (bytes === 0) return '0 B';
		const k = 1024;
		const sizes = ['B', 'KB', 'MB', 'GB'];
		const i = Math.floor(Math.log(bytes) / Math.log(k));
		return parseFloat((bytes / Math.pow(k, i)).toFixed(1)) + ' ' + sizes[i];
	}

	// --- File handling ---
	function handleFiles(fileList: FileList | File[]) {
		const newFiles: AttachedFile[] = Array.from(fileList).map(file => {
			const isImage = file.type.startsWith('image/') || /\.(jpg|jpeg|png|gif|webp|svg)$/i.test(file.name);
			return {
				id: genId(),
				file,
				type: isImage ? (file.type || 'image/unknown') : (file.type || 'application/octet-stream'),
				preview: isImage ? URL.createObjectURL(file) : null,
				uploadStatus: 'pending' as const,
			};
		});

		files = [...files, ...newFiles];

		newFiles.forEach(f => {
			setTimeout(() => {
				files = files.map(p => p.id === f.id ? { ...p, uploadStatus: 'uploading' as const } : p);
			}, 100);
			setTimeout(() => {
				files = files.map(p => p.id === f.id ? { ...p, uploadStatus: 'complete' as const } : p);
			}, 800 + Math.random() * 1000);
		});
	}

	function removeFile(id: string) {
		const file = files.find(f => f.id === id);
		if (file?.preview) URL.revokeObjectURL(file.preview);
		files = files.filter(f => f.id !== id);
	}

	function removePastedContent(id: string) {
		pastedContent = pastedContent.filter(c => c.id !== id);
	}

	// --- Screenshot ---
	async function takeScreenshot() {
		try {
			const stream = await navigator.mediaDevices.getDisplayMedia({ video: true });
			const video = document.createElement('video');
			video.srcObject = stream;
			await video.play();

			const canvas = document.createElement('canvas');
			canvas.width = video.videoWidth;
			canvas.height = video.videoHeight;
			canvas.getContext('2d')!.drawImage(video, 0, 0);

			stream.getTracks().forEach(t => t.stop());

			const blob = await new Promise<Blob>((resolve) =>
				canvas.toBlob(b => resolve(b!), 'image/png')
			);
			const file = new File([blob], `screenshot-${Date.now()}.png`, { type: 'image/png' });
			handleFiles([file]);
		} catch {
			// User cancelled the screen picker
		}
	}

	// --- Paste handling ---
	function handlePaste(e: ClipboardEvent) {
		const items = e.clipboardData?.items;
		if (!items) return;

		const pastedFiles: File[] = [];
		for (let i = 0; i < items.length; i++) {
			if (items[i].kind === 'file') {
				const file = items[i].getAsFile();
				if (file) pastedFiles.push(file);
			}
		}

		if (pastedFiles.length > 0) {
			e.preventDefault();
			handleFiles(pastedFiles);
			return;
		}

		const text = e.clipboardData?.getData('text') || '';
		if (text.length > 300) {
			e.preventDefault();
			pastedContent = [...pastedContent, {
				id: genId(),
				content: text,
				timestamp: new Date(),
			}];
		}
	}

	async function startRecording() {
		try {
			await recorder.start();
			voiceState = 'recording';
			micPermissionDenied = false;
		} catch (e: any) {
			if (e.name === 'NotAllowedError') micPermissionDenied = true;
			console.error('[Voice] start failed:', e);
		}
	}

	async function stopRecording() {
		voiceState = 'transcribing';
		try {
			const blob = await recorder.stop();
			const text = await transcribeAudio(blob);
			if (text) value = value ? value + ' ' + text : text;
		} catch (e) {
			console.error('[Voice] transcription failed:', e);
		}
		voiceState = 'idle';
	}

	function cancelRecording() {
		recorder.cancel();
		voiceState = 'idle';
	}

	// --- Send ---
	function handleSend() {
		if (!hasContent || disabled) return;
		const data: ChatInputSendData = {
			message: value,
			files: [...files],
			pastedContent: [...pastedContent],
			webSearchEnabled,
			style: activeStyle,
		};
		onSend(data);
		value = '';
		files = [];
		pastedContent = [];
		if (textareaEl) textareaEl.style.height = 'auto';
	}

	function onKeyDown(e: KeyboardEvent) {
		if (e.key === 'Enter' && !e.shiftKey) {
			e.preventDefault();
			handleSend();
		}
	}

	// --- Drag & Drop ---
	function onDragOver(e: DragEvent) {
		e.preventDefault();
		isDragging = true;
	}

	function onDragLeave(e: DragEvent) {
		e.preventDefault();
		isDragging = false;
	}

	function onDrop(e: DragEvent) {
		e.preventDefault();
		isDragging = false;
		if (e.dataTransfer?.files) handleFiles(e.dataTransfer.files);
	}

	function handleFileInput(e: Event) {
		const input = e.target as HTMLInputElement;
		if (input.files) handleFiles(input.files);
		input.value = '';
	}
</script>

{#snippet fileCard(file: AttachedFile)}
	<div class="relative group shrink-0 w-24 h-24 rounded-xl overflow-hidden border border-border bg-muted
		transition-all hover:border-muted-foreground/40">
		{#if file.type.startsWith('image/') && file.preview}
			<img src={file.preview} alt={file.file.name} class="w-full h-full object-cover" />
			<div class="absolute inset-0 bg-black/20 group-hover:bg-black/0 transition-colors"></div>
		{:else}
			<div class="w-full h-full p-2.5 flex flex-col justify-between">
				<div class="flex items-center gap-1.5">
					<div class="p-1 bg-border rounded">
						<FileText class="w-3.5 h-3.5 text-muted-foreground" />
					</div>
					<span class="text-[9px] font-medium text-muted-foreground uppercase tracking-wider truncate">
						{file.file.name.split('.').pop()}
					</span>
				</div>
				<div>
					<p class="text-[11px] text-foreground truncate" title={file.file.name}>{file.file.name}</p>
					<p class="text-[9px] text-muted-foreground">{formatFileSize(file.file.size)}</p>
				</div>
			</div>
		{/if}

		<button
			onclick={() => removeFile(file.id)}
			class="absolute top-1 end-1 p-1 bg-black/50 hover:bg-black/70 rounded-full text-white
				opacity-0 group-hover:opacity-100 transition-opacity"
		>
			<X class="w-3 h-3" />
		</button>

		{#if file.uploadStatus === 'uploading' || file.uploadStatus === 'pending'}
			<div class="absolute inset-0 bg-black/40 flex items-center justify-center">
				<Loader2 class="w-5 h-5 text-white animate-spin" />
			</div>
		{/if}
	</div>
{/snippet}

{#snippet pastedCard(content: PastedContent)}
	<div class="relative group shrink-0 w-28 h-28 rounded-2xl overflow-hidden border border-border bg-card
		p-3 flex flex-col justify-between shadow-sm">
		<div class="overflow-hidden w-full">
			<p class="text-[10px] text-muted-foreground leading-[1.4] font-mono break-words whitespace-pre-wrap
				select-none line-clamp-4">
				{content.content}
			</p>
		</div>
		<div class="flex items-center mt-2">
			<span class="thaana inline-flex items-center px-1.5 py-0.5 rounded border border-border bg-card
				text-[9px] font-bold text-muted-foreground uppercase tracking-wider">
				ޕޭސްޓް
			</span>
		</div>
		<button
			onclick={() => removePastedContent(content.id)}
			class="absolute top-2 end-2 p-0.5 bg-card border border-border rounded-full text-muted-foreground
				hover:text-foreground transition-colors shadow-sm
				opacity-0 group-hover:opacity-100"
		>
			<X class="w-2.5 h-2.5" />
		</button>
	</div>
{/snippet}

<!-- svelte-ignore a11y_no_static_element_interactions -->
<div
	class="relative w-full"
	ondragover={onDragOver}
	ondragleave={onDragLeave}
	ondrop={onDrop}
>
	<!-- Main container -->
	<div class="flex flex-col rounded-2xl border border-border bg-card
		shadow-sm hover:shadow-md focus-within:shadow-md
		focus-within:border-ring/50
		transition-all duration-200">

		<div class="flex flex-col px-3 pt-3 pb-3 gap-2">
			<!-- Attachments row -->
			{#if files.length > 0 || pastedContent.length > 0}
				<div class="flex gap-3 overflow-x-auto pb-2 px-1">
					{#each pastedContent as pc}
						{@render pastedCard(pc)}
					{/each}
					{#each files as f}
						{@render fileCard(f)}
					{/each}
				</div>
			{/if}

			<!-- Textarea area -->
			<div class="relative min-h-[2.5rem]">
				<textarea
					bind:this={textareaEl}
					bind:value
					onpaste={handlePaste}
					onkeydown={onKeyDown}
					{placeholder}
					dir="rtl"
					rows="1"
					style="min-height: 2.5rem; max-height: 384px;"
					class="thaana w-full bg-transparent text-foreground text-[18px]
						placeholder:text-muted-foreground resize-none overflow-hidden
						focus:outline-none leading-relaxed px-1 py-1"
					disabled={disabled}
					autofocus={autofocus}
				></textarea>
			</div>

			<!-- Action bar -->
			<div class="flex items-center gap-1">
				<!-- Plus menu (dropdown) -->
				<DropdownMenu.Root>
					<DropdownMenu.Trigger
						class="inline-flex items-center justify-center h-8 w-8 rounded-lg
							text-muted-foreground hover:text-foreground hover:bg-accent
							transition-colors duration-200 active:scale-95"
					>
						<Plus class="w-5 h-5" />
					</DropdownMenu.Trigger>
					<DropdownMenu.Content side="top" align="start" class="w-56">
						<!-- Add files -->
						<DropdownMenu.Item
							onclick={() => fileInputEl?.click()}
							class="thaana gap-3 text-base py-2.5"
						>
							<Paperclip class="w-5 h-5" />
							ފައިލް ނުވަތަ ފޮޓޯ
						</DropdownMenu.Item>

						<!-- Take screenshot -->
						<DropdownMenu.Item
							onclick={takeScreenshot}
							class="thaana gap-3 text-base py-2.5"
						>
							<Camera class="w-5 h-5" />
							ސްކްރީންޝޮޓް ނަގާ
						</DropdownMenu.Item>

						<DropdownMenu.Separator />

						<!-- Style submenu -->
						<DropdownMenu.Sub>
							<DropdownMenu.SubTrigger class="thaana gap-3 text-base py-2.5">
								<Feather class="w-5 h-5" />
								ސްޓައިލް
							</DropdownMenu.SubTrigger>
							<DropdownMenu.SubContent side="left" class="w-48">
								<DropdownMenu.RadioGroup bind:value={activeStyle}>
									{#each styles as style}
										<DropdownMenu.RadioItem value={style.id} class="thaana gap-3 text-base py-2.5">
											<Feather class="w-5 h-5" />
											{style.label}
											{#if activeStyle === style.id}
												<Check class="w-5 h-5 ms-auto text-primary" />
											{/if}
										</DropdownMenu.RadioItem>
									{/each}
								</DropdownMenu.RadioGroup>
							</DropdownMenu.SubContent>
						</DropdownMenu.Sub>
					</DropdownMenu.Content>
				</DropdownMenu.Root>

				<!-- Model switcher -->
				{#if models.length > 0}
					<DropdownMenu.Root>
						<DropdownMenu.Trigger
							class="inline-flex items-center justify-center h-8 gap-1.5 px-2 rounded-lg
								text-muted-foreground hover:text-foreground hover:bg-accent
								transition-colors duration-200 active:scale-95"
						>
							<Sparkles class="w-4.5 h-4.5" />
							<span class="thaana text-[11px] font-medium max-w-[120px] truncate">{modelDisplayName(selectedModel)}</span>
						</DropdownMenu.Trigger>
						<DropdownMenu.Content side="top" align="start" class="w-56">
							<DropdownMenu.RadioGroup bind:value={selectedModel}>
								{#each models as model}
									<DropdownMenu.RadioItem value={model} class="thaana gap-3 text-sm">
										<span class={selectedModel === model ? 'text-foreground font-medium' : ''}>{modelDisplayName(model)}</span>
										{#if selectedModel === model}
											<Check class="w-3.5 h-3.5 ms-auto text-primary" />
										{/if}
									</DropdownMenu.RadioItem>
								{/each}
							</DropdownMenu.RadioGroup>
						</DropdownMenu.Content>
					</DropdownMenu.Root>
				{/if}

				<div class="flex-1"></div>

				<!-- Active modifiers pills -->
				{#if webSearchEnabled || activeStyle !== 'normal'}
					<div class="flex items-center gap-1.5">
						{#if webSearchEnabled}
							<span class="thaana inline-flex items-center gap-1 px-2 py-0.5 text-[10px] text-primary bg-primary/10 rounded-full border border-primary/20">
								<Globe class="w-3 h-3" />
								ވެބް
							</span>
						{/if}
						{#if activeStyle !== 'normal'}
							<span class="thaana inline-flex items-center gap-1 px-2 py-0.5 text-[10px] text-primary bg-primary/10 rounded-full border border-primary/20">
								<Feather class="w-3 h-3" />
								{styles.find(s => s.id === activeStyle)?.label}
							</span>
						{/if}
					</div>
				{/if}

				<!-- Mic button -->
				{#if voiceState === 'idle'}
					<button
						onclick={startRecording}
						type="button"
						disabled={disabled}
						class="inline-flex items-center justify-center h-8 w-8 rounded-xl
							text-muted-foreground hover:text-foreground hover:bg-accent
							transition-colors duration-200 active:scale-95"
						aria-label="އަޑު ރެކޯޑް ކުރޭ"
					>
						<Mic class="w-4 h-4" />
					</button>
				{:else if voiceState === 'recording'}
					<div class="flex items-center gap-1">
						<WaveformVisualizer getFrequencyData={() => recorder.getFrequencyData()} />
						<button
							onclick={cancelRecording}
							type="button"
							class="inline-flex items-center justify-center h-8 w-8 rounded-xl
								text-muted-foreground hover:text-foreground hover:bg-accent
								transition-colors duration-200 active:scale-95"
							aria-label="ކެންސަލް"
						>
							<X class="w-4 h-4" />
						</button>
						<button
							onclick={stopRecording}
							type="button"
							class="inline-flex items-center justify-center h-8 w-8 rounded-xl
								bg-red-500 text-white hover:bg-red-600
								transition-colors duration-200 active:scale-95"
							aria-label="ހުއްޓާ"
						>
							<Square class="w-3.5 h-3.5" />
						</button>
					</div>
				{:else if voiceState === 'transcribing'}
					<div class="inline-flex items-center justify-center h-8 w-8">
						<Loader2 class="w-4 h-4 animate-spin text-muted-foreground" />
					</div>
				{/if}

				<!-- Send button -->
				<button
					onclick={handleSend}
					type="button"
					disabled={!hasContent || disabled}
					class="inline-flex items-center justify-center h-8 w-8 rounded-xl
						transition-colors duration-200 active:scale-95
						{hasContent ? 'bg-primary text-primary-foreground hover:bg-primary/90 shadow-sm' : 'text-muted-foreground opacity-50 cursor-default'}"
					aria-label="ފޮނުވާ"
				>
					<ArrowUp class="w-4 h-4" />
				</button>
			</div>
		</div>
	</div>

	<!-- Drag overlay -->
	{#if isDragging}
		<div class="absolute inset-0 bg-primary/5 border-2 border-dashed border-primary rounded-2xl z-50
			flex flex-col items-center justify-center backdrop-blur-sm pointer-events-none">
			<Archive class="w-10 h-10 text-primary mb-2 animate-bounce" />
			<p class="thaana text-primary font-medium">ފައިލް ދޫކޮށްލާ</p>
		</div>
	{/if}

	<!-- Hidden file input -->
	<input
		bind:this={fileInputEl}
		type="file"
		multiple
		class="hidden"
		onchange={handleFileInput}
	/>
</div>

// _archive/web_expo/components/ChatInput.tsx
import React, { useRef, useCallback, useState, useEffect, forwardRef, useImperativeHandle } from 'react';
import { View, Pressable, TextInput as RNTextInput } from 'react-native';
import { Text } from '@raalhu/ui';
import { modelDisplayName } from '@raalhu/shared';
import { createVoiceRecorder, type VoiceRecorder, type VoiceState } from '@raalhu/shared';
import {
	Plus, ArrowUp, X, Loader2, Sparkles, Paperclip, Camera, Feather, Check, Mic, Square, Globe, Archive
} from 'lucide-react';

export type StyleId = 'normal' | 'learning' | 'concise' | 'explanatory' | 'formal';

export interface ChatInputSendData {
	message: string;
	files: File[];
	pastedContent: string[];
	webSearchEnabled: boolean;
	style: StyleId;
}

interface ChatInputProps {
	value: string;
	onChangeValue: (v: string) => void;
	selectedModel: string;
	onChangeModel?: (m: string) => void;
	models?: string[];
	onSend: (data: ChatInputSendData) => void;
	disabled?: boolean;
	placeholder?: string;
}

export interface ChatInputHandle {
	focus: () => void;
}

const STYLES: { id: StyleId; label: string }[] = [
	{ id: 'normal', label: 'ނޯމަލް' },
	{ id: 'learning', label: 'ދަސްކުރުން' },
	{ id: 'concise', label: 'ކުރުކޮށް' },
	{ id: 'explanatory', label: 'ތަފްސީލީ' },
	{ id: 'formal', label: 'ރަސްމީ' },
];

export const ChatInput = forwardRef<ChatInputHandle, ChatInputProps>(function ChatInput(
	{
		value,
		onChangeValue,
		selectedModel,
		onChangeModel,
		models = [],
		onSend,
		disabled = false,
		placeholder = 'މެސެޖެއް ލިޔުއްވާ...',
	},
	ref
) {
	const textareaRef = useRef<HTMLTextAreaElement>(null);
	const fileInputRef = useRef<HTMLInputElement>(null);
	const [files, setFiles] = useState<File[]>([]);
	const [pastedContent, setPastedContent] = useState<string[]>([]);
	const [isDragging, setIsDragging] = useState(false);
	const [webSearchEnabled, setWebSearchEnabled] = useState(false);
	const [activeStyle, setActiveStyle] = useState<StyleId>('normal');
	const [showPlusMenu, setShowPlusMenu] = useState(false);
	const [showModelMenu, setShowModelMenu] = useState(false);
	const [showStyleMenu, setShowStyleMenu] = useState(false);
	const [voiceState, setVoiceState] = useState<VoiceState>('idle');
	const recorderRef = useRef<VoiceRecorder | null>(null);

	useImperativeHandle(ref, () => ({
		focus: () => textareaRef.current?.focus(),
	}));

	// Close menus on click outside
	const plusMenuRef = useRef<HTMLDivElement>(null);
	const modelMenuRef = useRef<HTMLDivElement>(null);

	useEffect(() => {
		function handleClick(e: MouseEvent) {
			if (showPlusMenu && plusMenuRef.current && !plusMenuRef.current.contains(e.target as Node)) {
				setShowPlusMenu(false);
				setShowStyleMenu(false);
			}
			if (showModelMenu && modelMenuRef.current && !modelMenuRef.current.contains(e.target as Node)) {
				setShowModelMenu(false);
			}
		}
		document.addEventListener('click', handleClick);
		return () => document.removeEventListener('click', handleClick);
	}, [showPlusMenu, showModelMenu]);

	useEffect(() => {
		return () => {
			recorderRef.current?.destroy();
		};
	}, []);

	// Auto-resize
	useEffect(() => {
		const el = textareaRef.current;
		if (el) {
			el.style.height = 'auto';
			el.style.height = Math.min(el.scrollHeight, 384) + 'px';
		}
	}, [value]);

	const hasContent = value.trim() || files.length > 0 || pastedContent.length > 0;

	const handleSend = useCallback(() => {
		if (!hasContent || disabled) return;
		onSend({
			message: value,
			files: [...files],
			pastedContent: [...pastedContent],
			webSearchEnabled,
			style: activeStyle,
		});
		onChangeValue('');
		setFiles([]);
		setPastedContent([]);
	}, [value, files, hasContent, disabled, webSearchEnabled, activeStyle, onSend, onChangeValue]);

	const handleKeyDown = useCallback((e: React.KeyboardEvent) => {
		if (e.key === 'Enter' && !e.shiftKey) {
			e.preventDefault();
			handleSend();
		}
	}, [handleSend]);

	const handleFileInput = useCallback((e: React.ChangeEvent<HTMLInputElement>) => {
		if (e.target.files) {
			setFiles(prev => [...prev, ...Array.from(e.target.files!)]);
		}
		e.target.value = '';
	}, []);

	const handleDrop = useCallback((e: React.DragEvent) => {
		e.preventDefault();
		setIsDragging(false);
		if (e.dataTransfer?.files) {
			setFiles(prev => [...prev, ...Array.from(e.dataTransfer.files)]);
		}
	}, []);

	const handlePaste = useCallback((e: React.ClipboardEvent) => {
		const items = e.clipboardData?.items;
		if (!items) return;
		const pastedFiles: File[] = [];
		let pastedText = '';
		for (let i = 0; i < items.length; i++) {
			if (items[i].kind === 'file') {
				const file = items[i].getAsFile();
				if (file) pastedFiles.push(file);
			} else if (items[i].kind === 'string' && items[i].type === 'text/plain') {
				pastedText = e.clipboardData?.getData('text/plain') || '';
			}
		}
		if (pastedFiles.length > 0) {
			e.preventDefault();
			setFiles(prev => [...prev, ...pastedFiles]);
		} else if (pastedText && (pastedText.length > 100 || pastedText.includes('\n'))) {
			e.preventDefault();
			setPastedContent(prev => [...prev, pastedText]);
		}
	}, []);

	const takeScreenshot = useCallback(async () => {
		setShowPlusMenu(false);
		try {
			const stream = await navigator.mediaDevices.getDisplayMedia({ video: true });
			const video = document.createElement('video');
			video.srcObject = stream;
			await video.play();
			const canvas = document.createElement('canvas');
			canvas.width = video.videoWidth;
			canvas.height = video.videoHeight;
			canvas.getContext('2d')!.drawImage(video, 0, 0);
			stream.getTracks().forEach(t => t.stop());
			const blob = await new Promise<Blob>((resolve) =>
				canvas.toBlob(b => resolve(b!), 'image/png')
			);
			const file = new File([blob], `screenshot-${Date.now()}.png`, { type: 'image/png' });
			setFiles(prev => [...prev, file]);
		} catch { /* user cancelled */ }
	}, []);

	const startRecording = useCallback(async () => {
		try {
			const rec = createVoiceRecorder();
			recorderRef.current = rec;
			await rec.start();
			setVoiceState('recording');
		} catch (e: any) {
			console.error('[Voice] start failed:', e);
		}
	}, []);

	const stopRecording = useCallback(async () => {
		setVoiceState('transcribing');
		try {
			const blob = await recorderRef.current!.stop();
		} catch (e) {
			console.error('[Voice] stop failed:', e);
		}
		setVoiceState('idle');
	}, [value, onChangeValue]);

	const cancelRecording = useCallback(() => {
		recorderRef.current?.cancel();
		setVoiceState('idle');
	}, []);

	return (
		<div
			className="relative w-full"
			onDragOver={(e) => { e.preventDefault(); setIsDragging(true); }}
			onDragLeave={(e) => { e.preventDefault(); setIsDragging(false); }}
			onDrop={handleDrop}
		>
			<div className="flex flex-col rounded-2xl border border-border bg-card
				shadow-sm hover:shadow-md focus-within:shadow-md
				focus-within:border-ring/50
				transition-all duration-200">

				<div className="flex flex-col px-3 pt-3 pb-3 gap-2">
					{/* Pasted content cards */}
					{pastedContent.length > 0 && (
						<div className="flex flex-col gap-1.5 px-1">
							{pastedContent.map((text, i) => (
								<div key={i} className="flex items-start gap-2 px-3 py-2 bg-muted/50 border border-border/50 rounded-lg" dir="rtl">
									<div className="flex-1 min-w-0">
										<span className="thaana text-[10px] text-muted-foreground/60 block mb-0.5">ޕޭސްޓް ކޮންޓެންޓް</span>
										<p className="text-xs text-muted-foreground font-mono truncate" dir="ltr">
											{text.slice(0, 80)}{text.length > 80 ? '...' : ''}
										</p>
									</div>
									<button
										onClick={() => setPastedContent(prev => prev.filter((_, j) => j !== i))}
										className="p-0.5 text-muted-foreground hover:text-foreground transition-colors shrink-0"
									>
										<X className="w-3 h-3" />
									</button>
								</div>
							))}
						</div>
					)}

					{/* File previews */}
					{files.length > 0 && (
						<div className="flex gap-2 overflow-x-auto pb-2 px-1">
							{files.map((f, i) => (
								<div key={i} className="relative group shrink-0 w-24 h-24 rounded-xl overflow-hidden border border-border bg-muted">
									{f.type.startsWith('image/') ? (
										<img src={URL.createObjectURL(f)} alt={f.name} className="w-full h-full object-cover" />
									) : (
										<div className="w-full h-full p-2.5 flex flex-col justify-between">
											<span className="text-[9px] font-medium text-muted-foreground uppercase">
												{f.name.split('.').pop()}
											</span>
											<div>
												<p className="text-[11px] text-foreground truncate">{f.name}</p>
												<p className="text-[9px] text-muted-foreground">{(f.size / 1024).toFixed(1)} KB</p>
											</div>
										</div>
									)}
									<button
										onClick={() => setFiles(prev => prev.filter((_, j) => j !== i))}
										className="absolute top-1 end-1 p-1 bg-black/50 hover:bg-black/70 rounded-full text-white
											opacity-0 group-hover:opacity-100 transition-opacity"
									>
										<X className="w-3 h-3" />
									</button>
								</div>
							))}
						</div>
					)}

					{/* Textarea */}
					<div className="relative min-h-[2.5rem]">
						<textarea
							ref={textareaRef}
							value={value}
							onChange={(e) => onChangeValue(e.target.value)}
							onKeyDown={handleKeyDown}
							onPaste={handlePaste}
							placeholder={placeholder}
							dir="rtl"
							rows={1}
							style={{ minHeight: '2.5rem', maxHeight: 384 }}
							className="thaana w-full bg-transparent text-foreground text-[18px]
								placeholder:text-muted-foreground resize-none overflow-hidden
								focus:outline-none leading-relaxed px-1 py-1"
							disabled={disabled}
						/>
					</div>

					{/* Action bar */}
					<div className="flex items-center gap-1">
						{/* Plus menu */}
						<div ref={plusMenuRef} className="relative">
							<button
								onClick={() => setShowPlusMenu(!showPlusMenu)}
								className="inline-flex items-center justify-center h-8 w-8 rounded-lg
									text-muted-foreground hover:text-foreground hover:bg-accent
									transition-colors duration-200 active:scale-95"
							>
								<Plus className="w-5 h-5" />
							</button>
							{showPlusMenu && (
								<div className="absolute bottom-full start-0 mb-1 w-56 bg-card border border-border rounded-lg shadow-lg z-50 py-1">
									<button
										onClick={() => { fileInputRef.current?.click(); setShowPlusMenu(false); }}
										className="thaana flex items-center gap-3 w-full px-3 py-2.5 text-sm hover:bg-accent transition-colors text-right"
										dir="rtl"
									>
										<Paperclip className="w-5 h-5 shrink-0" />
										ފައިލް ނުވަތަ ފޮޓޯ
									</button>
									<button
										onClick={takeScreenshot}
										className="thaana flex items-center gap-3 w-full px-3 py-2.5 text-sm hover:bg-accent transition-colors text-right"
										dir="rtl"
									>
										<Camera className="w-5 h-5 shrink-0" />
										ސްކްރީންޝޮޓް ނަގާ
									</button>
									<div className="h-px bg-border mx-2 my-1" />
									{/* Style submenu */}
									<div className="relative">
										<button
											onClick={() => setShowStyleMenu(!showStyleMenu)}
											className="thaana flex items-center gap-3 w-full px-3 py-2.5 text-sm hover:bg-accent transition-colors text-right"
											dir="rtl"
										>
											<Feather className="w-5 h-5 shrink-0" />
											ސްޓައިލް
										</button>
										{showStyleMenu && (
											<div className="absolute end-full top-0 me-1 w-48 bg-card border border-border rounded-lg shadow-lg py-1">
												{STYLES.map(s => (
													<button
														key={s.id}
														onClick={() => { setActiveStyle(s.id); setShowStyleMenu(false); setShowPlusMenu(false); }}
														className={`thaana flex items-center gap-3 w-full px-3 py-2.5 text-sm hover:bg-accent transition-colors text-right
															${activeStyle === s.id ? 'text-primary font-medium' : ''}`}
														dir="rtl"
													>
														<Feather className="w-5 h-5 shrink-0" />
														{s.label}
														{activeStyle === s.id && <Check className="w-5 h-5 ms-auto text-primary" />}
													</button>
												))}
											</div>
										)}
									</div>
								</div>
							)}
						</div>

						{/* Model switcher */}
						{models.length > 0 && (
							<div ref={modelMenuRef} className="relative">
								<button
									onClick={() => setShowModelMenu(!showModelMenu)}
									className="inline-flex items-center gap-1.5 h-8 px-2 rounded-lg
										text-muted-foreground hover:text-foreground hover:bg-accent
										transition-colors duration-200 active:scale-95"
								>
									<Sparkles className="w-4 h-4" />
									<span className="thaana text-[11px] font-medium max-w-[120px] truncate">
										{modelDisplayName(selectedModel)}
									</span>
								</button>
								{showModelMenu && (
									<div className="absolute bottom-full start-0 mb-1 w-56 bg-card border border-border rounded-lg shadow-lg z-50 py-1">
										{models.map(m => (
											<button
												key={m}
												onClick={() => { onChangeModel?.(m); setShowModelMenu(false); }}
												className={`thaana flex items-center gap-2 w-full px-3 py-2 text-sm hover:bg-accent transition-colors text-right
													${selectedModel === m ? 'text-foreground font-medium' : 'text-muted-foreground'}`}
												dir="rtl"
											>
												{selectedModel === m && <Check className="w-3.5 h-3.5 text-primary" />}
												{modelDisplayName(m)}
											</button>
										))}
									</div>
								)}
							</div>
						)}

						<div className="flex-1" />

						{/* Active modifier pills */}
						{(webSearchEnabled || activeStyle !== 'normal') && (
							<div className="flex items-center gap-1.5">
								{webSearchEnabled && (
									<span className="thaana inline-flex items-center gap-1 px-2 py-0.5 text-[10px] text-primary bg-primary/10 rounded-full border border-primary/20">
										<Globe className="w-3 h-3" />
										ވެބް
									</span>
								)}
								{activeStyle !== 'normal' && (
									<span className="thaana inline-flex items-center gap-1 px-2 py-0.5 text-[10px] text-primary bg-primary/10 rounded-full border border-primary/20">
										<Feather className="w-3 h-3" />
										{STYLES.find(s => s.id === activeStyle)?.label}
									</span>
								)}
							</div>
						)}

						{/* Mic button */}
						{voiceState === 'idle' && (
							<button
								onClick={startRecording}
								disabled={disabled}
								className="inline-flex items-center justify-center h-8 w-8 rounded-xl
									text-muted-foreground hover:text-foreground hover:bg-accent
									transition-colors duration-200 active:scale-95"
							>
								<Mic className="w-4 h-4" />
							</button>
						)}
						{voiceState === 'recording' && (
							<div className="flex items-center gap-1">
								<div className="flex items-center gap-0.5 px-1">
									{[...Array(8)].map((_, i) => (
										<div
											key={i}
											className="w-0.5 bg-red-400 rounded-full animate-pulse"
											style={{ height: 8 + Math.random() * 12, animationDelay: `${i * 0.1}s` }}
										/>
									))}
								</div>
								<button
									onClick={cancelRecording}
									className="inline-flex items-center justify-center h-8 w-8 rounded-xl
										text-muted-foreground hover:text-foreground hover:bg-accent
										transition-colors duration-200"
								>
									<X className="w-4 h-4" />
								</button>
								<button
									onClick={stopRecording}
									className="inline-flex items-center justify-center h-8 w-8 rounded-xl
										bg-red-500 text-white hover:bg-red-600 transition-colors"
								>
									<Square className="w-3.5 h-3.5" />
								</button>
							</div>
						)}
						{voiceState === 'transcribing' && (
							<div className="inline-flex items-center justify-center h-8 w-8">
								<Loader2 className="w-4 h-4 animate-spin text-muted-foreground" />
							</div>
						)}

						{/* Send button */}
						<button
							onClick={handleSend}
							disabled={!hasContent || disabled}
							className={`inline-flex items-center justify-center h-8 w-8 rounded-xl
								transition-colors duration-200 active:scale-95
								${hasContent && !disabled
									? 'bg-primary text-primary-foreground hover:bg-primary/90 shadow-sm'
									: 'text-muted-foreground opacity-50 cursor-default'}`}
						>
							<ArrowUp className="w-4 h-4" />
						</button>
					</div>
				</div>
			</div>

			{/* Drag overlay */}
			{isDragging && (
				<div className="absolute inset-0 bg-primary/5 border-2 border-dashed border-primary rounded-2xl z-50
					flex flex-col items-center justify-center backdrop-blur-sm pointer-events-none">
					<Archive className="w-10 h-10 text-primary mb-2 animate-bounce" />
					<p className="thaana text-primary font-medium">ފައިލް ދޫކޮށްލާ</p>
				</div>
			)}

			{/* Hidden file input */}
			<input
				ref={fileInputRef}
				type="file"
				multiple
				className="hidden"
				onChange={handleFileInput}
			/>
		</div>
	);
});
