// _archive/web_expo/components/tool-renderers/DefaultRenderer.tsx
import React from 'react';

interface DefaultRendererProps {
	result?: Record<string, unknown> | string;
}

export function DefaultRenderer({ result }: DefaultRendererProps) {
	if (!result) return null;

	return (
		<pre className="text-[10px] text-muted-foreground font-mono whitespace-pre-wrap overflow-x-auto mt-1 max-h-[200px] overflow-y-auto" dir="ltr">
			{typeof result === 'string' ? result : JSON.stringify(result, null, 2)}
		</pre>
	);
}

// frontend/src/lib/components/tool-renderers/DefaultRenderer.svelte
<script lang="ts">
	let { result = undefined }: {
		result?: Record<string, unknown> | string;
	} = $props();
</script>

{#if result}
	<pre class="text-[10px] text-muted-foreground font-mono whitespace-pre-wrap overflow-x-auto mt-1 max-h-[200px] overflow-y-auto" dir="ltr">{typeof result === 'string' ? result : JSON.stringify(result, null, 2)}</pre>
{/if}
