// apps/desktop/src/renderer/components/tool-renderers/SkillRenderer.tsx
import React from 'react';

interface SkillRendererProps {
	result?: Record<string, unknown> | string;
	status: 'running' | 'done' | 'error';
}

export function SkillRenderer({ result, status }: SkillRendererProps) {
	if (status !== 'error' || !result) return null;

	const errorMsg = typeof result === 'string'
		? result
		: (result as Record<string, unknown>).error as string || '';

	if (!errorMsg) return null;

	return <p className="text-xs text-destructive mt-1" dir="ltr">{errorMsg}</p>;
}

// frontend/src/lib/components/tool-renderers/SkillRenderer.svelte
<script lang="ts">
	let { result = undefined, status = 'running' }: {
		args: Record<string, unknown>;
		result?: Record<string, unknown> | string;
		status: 'running' | 'done' | 'error';
	} = $props();

	let errorMsg = $derived.by(() => {
		if (status !== 'error' || !result) return '';
		if (typeof result === 'string') return result;
		return (result as Record<string, unknown>).error as string || '';
	});
</script>

{#if status === 'error' && errorMsg}
	<p class="text-xs text-destructive mt-1" dir="ltr">{errorMsg}</p>
{/if}
