// _archive/web_expo/components/ArtifactPreview.tsx
import React, { useState, useRef, useEffect, useCallback } from 'react';
import { Download, RefreshCw, X, Loader2, FileText } from 'lucide-react';
import type { Artifact } from '../lib/agent/types';

type PreviewType = 'docx' | 'xlsx' | 'pdf' | 'image' | 'text' | 'none';

interface ArtifactPreviewProps {
	artifact: Artifact;
	onClose: () => void;
	onDownload: () => void;
}

function getExt(filename: string): string {
	return filename.split('.').pop()?.toLowerCase() || '';
}

export function ArtifactPreview({ artifact, onClose, onDownload }: ArtifactPreviewProps) {
	const [previewType, setPreviewType] = useState<PreviewType>('none');
	const [loading, setLoading] = useState(true);
	const [rendering, setRendering] = useState(false);
	const [error, setError] = useState('');
	const [textContent, setTextContent] = useState('');
	const [xlsxSheets, setXlsxSheets] = useState<{ name: string; html: string }[]>([]);
	const [xlsxActiveSheet, setXlsxActiveSheet] = useState(0);
	const docxContainerRef = useRef<HTMLDivElement>(null);
	const docxBufferRef = useRef<ArrayBuffer | null>(null);

	const loadPreview = useCallback(async (art: typeof artifact) => {
		setLoading(true);
		setError('');
		setTextContent('');
		setXlsxSheets([]);
		setXlsxActiveSheet(0);
		setPreviewType('none');
		docxBufferRef.current = null;

		const ext = getExt(art.filename);
		const mime = art.mimeType;

		try {
			if (['docx', 'doc'].includes(ext)) {
				const res = await fetch(art.url);
				docxBufferRef.current = await res.arrayBuffer();
				setPreviewType('docx');
			} else if (['xlsx', 'xls'].includes(ext)) {
				const XLSX = await import('xlsx');
				const res = await fetch(art.url);
				const buf = await res.arrayBuffer();
				const wb = XLSX.read(buf, { type: 'array' });
				setXlsxSheets(wb.SheetNames.map(name => ({
					name,
					html: XLSX.utils.sheet_to_html(wb.Sheets[name])
				})));
				setPreviewType('xlsx');
			} else if (ext === 'csv') {
				const XLSX = await import('xlsx');
				const res = await fetch(art.url);
				const text = await res.text();
				const wb = XLSX.read(text, { type: 'string' });
				setXlsxSheets(wb.SheetNames.map(name => ({
					name,
					html: XLSX.utils.sheet_to_html(wb.Sheets[name])
				})));
				setPreviewType('xlsx');
			} else if (ext === 'pdf') {
				setPreviewType('pdf');
			} else if (mime.startsWith('image/')) {
				setPreviewType('image');
			} else if (
				mime.startsWith('text/') ||
				['txt', 'json', 'md', 'py', 'js', 'html', 'xml'].includes(ext)
			) {
				const res = await fetch(art.url);
				setTextContent(await res.text());
				setPreviewType('text');
			} else {
				setPreviewType('none');
			}
		} catch (err: any) {
			setError(err.message || 'Preview failed');
		} finally {
			setLoading(false);
		}
	}, []);

	// Load on mount and artifact change
	useEffect(() => {
		loadPreview(artifact);
	}, [artifact, loadPreview]);

	// Render DOCX when container and buffer are ready
	useEffect(() => {
		if (previewType !== 'docx' || !docxContainerRef.current || !docxBufferRef.current) return;
		setRendering(true);
		(async () => {
			try {
				const { renderAsync } = await import('docx-preview');
				docxContainerRef.current!.innerHTML = '';
				await renderAsync(docxBufferRef.current!, docxContainerRef.current!, undefined, {
					className: 'docx',
					inWrapper: true,
					ignoreWidth: true,
					ignoreHeight: true,
					ignoreFonts: false,
					breakPages: false,
					renderHeaders: true,
					renderFooters: true,
					renderFootnotes: true,
					renderEndnotes: true
				});
			} catch (err: any) {
				setError(err.message || 'DOCX render failed');
			} finally {
				setRendering(false);
			}
		})();
	}, [previewType]);

	const typeLabel = getExt(artifact.filename).toUpperCase();

	return (
		<div className="flex flex-col h-full bg-background animate-sheet-in border-s border-border">
			{/* Header */}
			<div className="flex items-center gap-2.5 px-4 py-3 border-b border-border shrink-0">
				<div className="flex-1 min-w-0 pe-4 truncate">
					<span className="thaana text-sm font-medium text-foreground">{artifact.label}</span>
					<span className="text-sm text-muted-foreground"> · {typeLabel}</span>
				</div>
				<button
					onClick={onDownload}
					className="p-1.5 rounded-sm border border-border bg-muted/60 hover:bg-accent text-muted-foreground hover:text-foreground transition-colors"
					title="Download"
				>
					<Download size={16} />
				</button>
				<button
					onClick={() => loadPreview(artifact)}
					className="p-1.5 rounded-sm text-muted-foreground hover:text-foreground hover:bg-accent transition-colors"
					title="Refresh"
				>
					<RefreshCw size={16} />
				</button>
				<button
					onClick={onClose}
					className="p-1.5 rounded-md hover:bg-accent text-muted-foreground hover:text-foreground transition-colors"
					title="Close"
				>
					<X size={16} />
				</button>
			</div>

			{/* Preview body */}
			<div className="flex-1 overflow-auto relative min-h-0">
				{(loading || rendering) && (
					<div className="flex items-center justify-center h-full">
						<Loader2 size={24} className="animate-spin text-muted-foreground" />
					</div>
				)}

				{!loading && !rendering && error && (
					<div className="flex flex-col items-center justify-center h-full gap-2 text-muted-foreground">
						<span className="thaana text-sm">ފައިލް ލޯޑެއް ނުކުރެވުނު</span>
						<button
							onClick={onDownload}
							className="thaana px-4 py-2 rounded-lg bg-primary text-primary-foreground text-sm hover:bg-primary/90 transition-colors"
						>
							ޑައުންލޯޑް
						</button>
					</div>
				)}

				{/* DOCX */}
				{previewType === 'docx' && (
					<div
						ref={docxContainerRef}
						className="docx-host"
						style={{ display: loading || rendering || error ? 'none' : 'flex' }}
					/>
				)}

				{/* XLSX / CSV */}
				{previewType === 'xlsx' && !loading && !error && (
					<>
						{xlsxSheets.length > 1 && (
							<div className="sticky top-0 z-10 flex gap-0.5 px-3 pt-2 pb-1 bg-background border-b border-border">
								{xlsxSheets.map((sheet, idx) => (
									<button
										key={idx}
										onClick={() => setXlsxActiveSheet(idx)}
										className={`px-3 py-1.5 text-xs rounded-t-md transition-colors
											${idx === xlsxActiveSheet ? 'bg-muted text-foreground font-medium' : 'text-muted-foreground hover:text-foreground hover:bg-muted/50'}`}
									>
										{sheet.name}
									</button>
								))}
							</div>
						)}
						<div
							className="xlsx-host p-4 overflow-auto"
							dangerouslySetInnerHTML={{ __html: xlsxSheets[xlsxActiveSheet]?.html || '' }}
						/>
					</>
				)}

				{/* PDF */}
				{previewType === 'pdf' && !loading && !error && (
					<iframe
						src={artifact.url}
						className="w-full h-full border-0"
						title={artifact.label}
					/>
				)}

				{/* Image */}
				{previewType === 'image' && !loading && !error && (
					<div className="flex items-center justify-center p-6 h-full">
						<img
							src={artifact.url}
							alt={artifact.label}
							className="max-w-full max-h-full object-contain rounded"
						/>
					</div>
				)}

				{/* Text / Code */}
				{previewType === 'text' && !loading && !error && (
					<div className="p-5">
						<pre className="text-sm text-foreground font-mono whitespace-pre-wrap leading-relaxed">{textContent}</pre>
					</div>
				)}

				{/* Unsupported */}
				{previewType === 'none' && !loading && !error && (
					<div className="flex flex-col items-center justify-center h-full gap-3 text-muted-foreground">
						<FileText size={48} className="opacity-40 text-muted-foreground" />
						<span className="text-sm">Preview not available</span>
						<button
							onClick={onDownload}
							className="px-4 py-2 rounded-lg bg-primary text-primary-foreground text-sm hover:bg-primary/90 transition-colors"
						>
							Download
						</button>
					</div>
				)}
			</div>
		</div>
	);
}

// frontend/src/lib/components/ArtifactPreview.svelte
<script lang="ts">
	import { X, Download, RotateCw, Loader2, FileText } from 'lucide-svelte';
	import type { Artifact } from '$lib/agent/types';

	let {
		artifact,
		onClose,
		onDownload
	}: {
		artifact: Artifact;
		onClose: () => void;
		onDownload: () => void;
	} = $props();

	type PreviewType = 'docx' | 'xlsx' | 'pdf' | 'image' | 'text' | 'none';

	let previewType = $state<PreviewType>('none');
	let loading = $state(true);
	let rendering = $state(false);
	let error = $state('');

	// DOCX: docx-preview renders into a DOM container
	let docxContainer = $state<HTMLDivElement>();
	let docxBuffer = $state<ArrayBuffer | null>(null);

	// XLSX/CSV: SheetJS parsed sheets
	let xlsxSheets = $state<{ name: string; html: string }[]>([]);
	let xlsxActiveSheet = $state(0);

	// Text/code
	let textContent = $state('');

	function getExt(filename: string): string {
		return filename.split('.').pop()?.toLowerCase() || '';
	}

	function getTypeLabel(filename: string, _mimeType: string): string {
		return getExt(filename).toUpperCase();
	}

	// Load preview data when artifact changes
	$effect(() => {
		const _art = artifact;
		loadPreview(_art);
	});

	// Render DOCX when container becomes available after previewType is set
	$effect(() => {
		if (docxContainer && docxBuffer && previewType === 'docx') {
			rendering = true;
			renderDocx(docxContainer, docxBuffer)
				.catch((err) => {
					error = err.message || 'DOCX render failed';
				})
				.finally(() => {
					rendering = false;
				});
		}
	});

	async function loadPreview(art: Artifact) {
		loading = true;
		error = '';
		docxBuffer = null;
		xlsxSheets = [];
		xlsxActiveSheet = 0;
		textContent = '';
		previewType = 'none';

		const ext = getExt(art.filename);
		const mime = art.mimeType;

		try {
			if (['docx', 'doc'].includes(ext)) {
				const res = await fetch(art.url);
				docxBuffer = await res.arrayBuffer();
				previewType = 'docx';
			} else if (['xlsx', 'xls'].includes(ext)) {
				const XLSX = await import('xlsx');
				const res = await fetch(art.url);
				const buf = await res.arrayBuffer();
				const wb = XLSX.read(buf, { type: 'array' });
				xlsxSheets = wb.SheetNames.map((name) => ({
					name,
					html: XLSX.utils.sheet_to_html(wb.Sheets[name])
				}));
				previewType = 'xlsx';
			} else if (ext === 'csv') {
				const XLSX = await import('xlsx');
				const res = await fetch(art.url);
				const text = await res.text();
				const wb = XLSX.read(text, { type: 'string' });
				xlsxSheets = wb.SheetNames.map((name) => ({
					name,
					html: XLSX.utils.sheet_to_html(wb.Sheets[name])
				}));
				previewType = 'xlsx';
			} else if (ext === 'pdf') {
				previewType = 'pdf';
			} else if (mime.startsWith('image/')) {
				previewType = 'image';
			} else if (
				mime.startsWith('text/') ||
				['txt', 'json', 'md', 'py', 'js', 'html', 'xml'].includes(ext)
			) {
				const res = await fetch(art.url);
				textContent = await res.text();
				previewType = 'text';
			} else {
				previewType = 'none';
			}
		} catch (err: any) {
			error = err.message || 'Preview failed';
		} finally {
			loading = false;
		}
	}

	async function renderDocx(container: HTMLDivElement, buffer: ArrayBuffer) {
		const { renderAsync } = await import('docx-preview');
		container.innerHTML = '';
		await renderAsync(buffer, container, undefined, {
			className: 'docx',
			inWrapper: true,
			ignoreWidth: false,
			ignoreHeight: false,
			ignoreFonts: false,
			breakPages: true,
			renderHeaders: true,
			renderFooters: true,
			renderFootnotes: true,
			renderEndnotes: true
		});
	}

	function switchSheet(idx: number) {
		xlsxActiveSheet = idx;
	}
</script>

<div class="flex flex-col h-full bg-background">
	<!-- Header -->
	<div class="flex items-center gap-2.5 px-4 py-3 border-b border-border shrink-0">
		<div class="flex-1 min-w-0 pr-4 truncate">
			<span class="thaana text-sm font-medium text-foreground">{artifact.label}</span>
			<span class="text-sm text-muted-foreground"> · {getTypeLabel(artifact.filename, artifact.mimeType)}</span>
		</div>
		<button
			onclick={onDownload}
			class="p-1.5 rounded-sm border border-white/20 bg-muted/60 hover:bg-black hover:border-black text-muted-foreground hover:text-foreground transition-colors"
			title="Download"
		>
			<Download class="w-3.5 h-3.5" />
		</button>
		<button
			onclick={() => loadPreview(artifact)}
			class="p-1.5 rounded-sm text-muted-foreground hover:text-foreground hover:bg-accent transition-colors"
			title="Refresh"
		>
			<RotateCw class="w-3.5 h-3.5" />
		</button>
		<button
			onclick={onClose}
			class="p-1.5 rounded-md hover:bg-accent text-muted-foreground hover:text-foreground transition-colors"
			title="Close"
		>
			<X class="w-3.5 h-3.5" />
		</button>
	</div>

	<!-- Preview body -->
	<div class="flex-1 overflow-auto relative">
		{#if loading || rendering}
			<div class="flex items-center justify-center h-full">
				<Loader2 class="w-6 h-6 animate-spin text-muted-foreground" />
			</div>
		{:else if error}
			<div class="flex flex-col items-center justify-center h-full gap-2 text-muted-foreground">
				<span class="thaana text-sm">ފައިލް ލޯޑެއް ނުކުރެވުނު</span>
				<button
					onclick={onDownload}
					class="thaana px-4 py-2 rounded-lg bg-primary text-primary-foreground text-sm hover:bg-primary/90 transition-colors"
				>
					ޑައުންލޯޑް
				</button>
			</div>
		{/if}

		<!-- DOCX: docx-preview renders into this container -->
		{#if previewType === 'docx'}
			<div
				bind:this={docxContainer}
				class="docx-host min-h-full"
				class:hidden={loading || rendering || !!error}
			></div>
		{/if}

		<!-- XLSX / CSV: sheet tabs + HTML table -->
		{#if previewType === 'xlsx' && !loading && !error}
			{#if xlsxSheets.length > 1}
				<div class="sticky top-0 z-10 flex gap-0.5 px-3 pt-2 pb-1 bg-background border-b border-border">
					{#each xlsxSheets as sheet, idx}
						<button
							onclick={() => switchSheet(idx)}
							class="px-3 py-1.5 text-xs rounded-t-md transition-colors {idx === xlsxActiveSheet
								? 'bg-muted text-foreground font-medium'
								: 'text-muted-foreground hover:text-foreground hover:bg-muted/50'}"
						>
							{sheet.name}
						</button>
					{/each}
				</div>
			{/if}
			<div class="xlsx-host p-4 overflow-auto">
				{@html xlsxSheets[xlsxActiveSheet]?.html || ''}
			</div>
		{/if}

		<!-- PDF: native browser rendering -->
		{#if previewType === 'pdf' && !loading && !error}
			<iframe
				src={artifact.url}
				class="w-full h-full border-0"
				title={artifact.label}
			></iframe>
		{/if}

		<!-- Image -->
		{#if previewType === 'image' && !loading && !error}
			<div class="flex items-center justify-center p-6 h-full">
				<img
					src={artifact.url}
					alt={artifact.label}
					class="max-w-full max-h-full object-contain rounded"
				/>
			</div>
		{/if}

		<!-- Text / Code -->
		{#if previewType === 'text' && !loading && !error}
			<div class="p-5">
				<pre class="text-sm text-foreground font-mono whitespace-pre-wrap leading-relaxed">{textContent}</pre>
			</div>
		{/if}

		<!-- Unsupported -->
		{#if previewType === 'none' && !loading && !error}
			<div class="flex flex-col items-center justify-center h-full gap-3 text-muted-foreground">
				<FileText class="w-12 h-12 opacity-40" />
				<span class="text-sm">Preview not available</span>
				<button
					onclick={onDownload}
					class="px-4 py-2 rounded-lg bg-primary text-primary-foreground text-sm hover:bg-primary/90 transition-colors"
				>
					Download
				</button>
			</div>
		{/if}
	</div>
</div>

<style>
	/* docx-preview: page wrapper styling */
	:global(.docx-host .docx-wrapper) {
		background: #e8e8e8;
		padding: 20px;
		min-height: 100%;
	}

	:global(.docx-host .docx-wrapper > section.docx) {
		background: white;
		box-shadow: 0 1px 6px rgba(0, 0, 0, 0.15);
		margin: 0 auto 20px;
	}

	/* xlsx: table styling */
	:global(.xlsx-host table) {
		border-collapse: collapse;
		width: 100%;
		font-size: 13px;
	}

	:global(.xlsx-host th),
	:global(.xlsx-host td) {
		border: 1px solid oklch(0.35 0 0);
		padding: 5px 10px;
		text-align: start;
		white-space: nowrap;
		max-width: 300px;
		overflow: hidden;
		text-overflow: ellipsis;
		color: oklch(0.9 0 0);
	}

	:global(.xlsx-host th) {
		background: oklch(0.22 0 0);
		font-weight: 600;
		color: oklch(0.7 0 0);
	}

	:global(.xlsx-host tr:nth-child(even) td) {
		background: oklch(0.16 0 0);
	}

	:global(.xlsx-host tr:hover td) {
		background: oklch(0.2 0.01 180);
	}
</style>
