// frontend/src/lib/components/tool-renderers/StepRow.svelte
<script lang="ts">
	import type { Component, Snippet } from 'svelte';
	import { ChevronDown, ChevronLeft } from 'lucide-svelte';

	let {
		icon,
		label,
		shimmer = false,
		children
	}: {
		icon: Component;
		label: string;
		shimmer?: boolean;
		children?: Snippet;
	} = $props();

	let expanded = $state(false);
	let expandable = $derived(!!children && !shimmer);
</script>

<div class="mb-0.5">
	<button
		onclick={() => { if (expandable) expanded = !expanded; }}
		class="group/step inline-flex items-center gap-1.5 h-7 text-xs transition-colors"
	>
		<svelte:component this={icon} class="w-3 h-3 text-muted-foreground/60 shrink-0" />

		<span
			class="thaana text-xs text-muted-foreground/70
				{shimmer ? 'step-shimmer' : ''}"
		>
			{label}
		</span>

		{#if expandable}
			<span class="{expanded ? 'opacity-100' : 'opacity-0 group-hover/step:opacity-100'} transition-opacity duration-150">
				{#if expanded}
					<ChevronDown class="w-3 h-3 text-muted-foreground/40" />
				{:else}
					<ChevronLeft class="w-3 h-3 text-muted-foreground/40" />
				{/if}
			</span>
		{/if}
	</button>

	{#if children && expanded}
		<div class="mr-6 pb-1.5">
			{@render children()}
		</div>
	{/if}
</div>

<style>
	@keyframes step-shimmer {
		0% {
			background-position: 200% center;
		}
		100% {
			background-position: -200% center;
		}
	}

	.step-shimmer {
		background: linear-gradient(
			90deg,
			var(--muted-foreground) 0%,
			var(--muted-foreground) 35%,
			var(--primary) 50%,
			var(--muted-foreground) 65%,
			var(--muted-foreground) 100%
		);
		background-size: 200% 100%;
		background-clip: text;
		-webkit-background-clip: text;
		-webkit-text-fill-color: transparent;
		animation: step-shimmer 2s ease-in-out infinite;
	}
</style>

// _archive/web_expo/components/tool-renderers/StepRow.tsx
import React, { useState } from 'react';
import { ChevronDown, ChevronLeft } from 'lucide-react';

interface StepRowProps {
	icon: React.ReactNode;
	label: string;
	shimmer?: boolean;
	children?: React.ReactNode;
}

export function StepRow({ icon, label, shimmer = false, children }: StepRowProps) {
	const [expanded, setExpanded] = useState(false);
	const expandable = !!children && !shimmer;

	return (
		<div className="mb-0.5">
			<button
				onClick={() => { if (expandable) setExpanded(!expanded); }}
				className="group/step inline-flex items-center gap-1.5 h-7 text-xs transition-colors"
			>
				<span className="text-muted-foreground/60 shrink-0 text-xs">{icon}</span>
				<span className={`thaana text-xs text-muted-foreground/70 ${shimmer ? 'step-shimmer' : ''}`}>
					{label}
				</span>
				{expandable && (
					<span className={`${expanded ? 'opacity-100' : 'opacity-0 group-hover/step:opacity-100'} transition-opacity duration-150`}>
						{expanded ? <ChevronDown size={12} className="text-muted-foreground/40" /> : <ChevronLeft size={12} className="text-muted-foreground/40" />}
					</span>
				)}
			</button>

			{children && expanded && (
				<div className="me-6 pb-1.5">
					{children}
				</div>
			)}
		</div>
	);
}
